// <auto-generated />
using System;
using MiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaBodega.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520124609_AgregarEntidadesSistemaCafe")]
    partial class AgregarEntidadesSistemaCafe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiApi.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.AuditoriaOperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("Detalles")
                        .HasColumnType("text")
                        .HasColumnName("detalles");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad_afectada");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.HasKey("Id")
                        .HasName("pk_auditorias");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_auditorias_admin_user_id");

                    b.ToTable("auditorias", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_nombre");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("seccion_id");

                    b.Property<int>("TipoCafeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cafe_id");

                    b.HasKey("Id")
                        .HasName("pk_inventarios");

                    b.HasIndex("TipoCafeId")
                        .HasDatabaseName("ix_inventarios_tipo_cafe_id");

                    b.HasIndex("SeccionId", "TipoCafeId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventarios_seccion_id_tipo_cafe_id");

                    b.ToTable("inventarios", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.MovimientoEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("seccion_id");

                    b.Property<int>("TipoCafeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cafe_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_entrada");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_movimientos_entrada_admin_user_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_movimientos_entrada_cliente_id");

                    b.HasIndex("SeccionId")
                        .HasDatabaseName("ix_movimientos_entrada_seccion_id");

                    b.HasIndex("TipoCafeId")
                        .HasDatabaseName("ix_movimientos_entrada_tipo_cafe_id");

                    b.ToTable("movimientos_entrada", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.MovimientoSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("seccion_id");

                    b.Property<int>("TipoCafeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cafe_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_salida");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_movimientos_salida_admin_user_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_movimientos_salida_cliente_id");

                    b.HasIndex("SeccionId")
                        .HasDatabaseName("ix_movimientos_salida_seccion_id");

                    b.HasIndex("TipoCafeId")
                        .HasDatabaseName("ix_movimientos_salida_tipo_cafe_id");

                    b.ToTable("movimientos_salida", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.SeccionAlmacenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_secciones");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_secciones_nombre");

                    b.ToTable("secciones", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.TipoCafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipos_cafe");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_cafe_nombre");

                    b.ToTable("tipos_cafe", (string)null);
                });

            modelBuilder.Entity("MiApi.Entities.AuditoriaOperacion", b =>
                {
                    b.HasOne("MiApi.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditorias_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("MiApi.Entities.Inventario", b =>
                {
                    b.HasOne("MiApi.Entities.SeccionAlmacenamiento", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventarios_secciones_seccion_id");

                    b.HasOne("MiApi.Entities.TipoCafe", "TipoCafe")
                        .WithMany()
                        .HasForeignKey("TipoCafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventarios_tipos_cafe_tipo_cafe_id");

                    b.Navigation("Seccion");

                    b.Navigation("TipoCafe");
                });

            modelBuilder.Entity("MiApi.Entities.MovimientoEntrada", b =>
                {
                    b.HasOne("MiApi.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_entrada_admin_users_admin_user_id");

                    b.HasOne("MiApi.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_entrada_clientes_cliente_id");

                    b.HasOne("MiApi.Entities.SeccionAlmacenamiento", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_entrada_secciones_seccion_id");

                    b.HasOne("MiApi.Entities.TipoCafe", "TipoCafe")
                        .WithMany()
                        .HasForeignKey("TipoCafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_entrada_tipos_cafe_tipo_cafe_id");

                    b.Navigation("AdminUser");

                    b.Navigation("Cliente");

                    b.Navigation("Seccion");

                    b.Navigation("TipoCafe");
                });

            modelBuilder.Entity("MiApi.Entities.MovimientoSalida", b =>
                {
                    b.HasOne("MiApi.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_salida_admin_users_admin_user_id");

                    b.HasOne("MiApi.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_salida_clientes_cliente_id");

                    b.HasOne("MiApi.Entities.SeccionAlmacenamiento", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_salida_secciones_seccion_id");

                    b.HasOne("MiApi.Entities.TipoCafe", "TipoCafe")
                        .WithMany()
                        .HasForeignKey("TipoCafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_salida_tipos_cafe_tipo_cafe_id");

                    b.Navigation("AdminUser");

                    b.Navigation("Cliente");

                    b.Navigation("Seccion");

                    b.Navigation("TipoCafe");
                });
#pragma warning restore 612, 618
        }
    }
}
